import type { Metadata } from 'next';
import { Chewy, Geist, Geist_Mono } from 'next/font/google';
import '@/style/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});
const chewySans = Chewy({
    weight: '400', // Укажите доступный вес шрифта
    variable: '--font-chewy',
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'SALE | SHOP',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${chewySans.variable}`}>
                {children}
            </body>
        </html>
    );
}
